webtalk_init -webtalk_dir /home/ugrad/repo/gateware/AddDivideChop/average_ip/average_ip.sim/sim_1/behav/xsim/xsim.dir/down_avg_2_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct  5 08:57:09 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "206010812_1777494936_210693615_003" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d3ad8e27-2a39-4678-8808-d5eb96525e81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f11f351e3dd4061af9b37bbeab77811" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "97" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1802.022 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3848856581 -regid "206010812_1777494936_210693615_003" -xml /home/ugrad/repo/gateware/AddDivideChop/average_ip/average_ip.sim/sim_1/behav/xsim/xsim.dir/down_avg_2_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ugrad/repo/gateware/AddDivideChop/average_ip/average_ip.sim/sim_1/behav/xsim/xsim.dir/down_avg_2_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ugrad/repo/gateware/AddDivideChop/average_ip/average_ip.sim/sim_1/behav/xsim/xsim.dir/down_avg_2_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
